default_platform(:ios)

desc "Test"
lane :test do |options|
  xctest(
    workspace: "VersionUpdater.xcworkspace",
    scheme: "VersionUpdater",
    destination: "platform=iOS Simulator,name=iPhone 11,OS=14.0",
  )
end

