default_platform(:ios)

desc "Test"
lane :test do |options|
  xctest(
    workspace: "VersionUpdater.xcworkspace",
    scheme: "VersionUpdater",
    destination: "platform=iOS Simulator,name=iPhone X,OS=11.3",
  )
end

